In [1]:
import numpy as np
import pandas as pd

#### Question 1

In [30]:
np.__version__

'2.1.3'

In [31]:
pd.__version__

'2.2.3'

#### Question 2

In [32]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [34]:
df['fuel_type'].nunique()

3

In [35]:
df.shape

(10000, 11)

#### Question 3

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   model_year           10000 non-null  int64  
 1   origin               10000 non-null  object 
 2   fuel_type            10000 non-null  object 
 3   drivetrain           10000 non-null  object 
 4   num_doors            10000 non-null  int64  
 5   engine_displacement  10000 non-null  int64  
 6   num_cylinders        10000 non-null  int64  
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64  
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB


In [38]:
df.fuel_efficiency_mpg.max()


41.2

In [39]:
df.horsepower.median()

254.0

In [40]:
(df['horsepower'].fillna(mode_value)).median()

252.0

#### Question 4

In [ ]:
df['Make'].value_counts()[0:3]

#### Question 5

In [ ]:
df_Audi = df[df['Make']=='Audi']
df_Audi.groupby('Make')['Model'].nunique()

In [ ]:
len(df.isnull().sum()[df.isnull().sum() > 1])

#### Question 6

In [ ]:
df.head()

In [ ]:
df['Engine Cylinders'].median()

In [ ]:
mode_value = df['Engine Cylinders'].mode()[0]
mode_value

In [ ]:
df['Engine Cylinders'].isnull().sum()

In [ ]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(mode_value)

In [ ]:
df['Engine Cylinders'].isnull().sum()

In [ ]:
df['Engine Cylinders'].median()

In [41]:
df_lotus = df[df['origin']== 'Asia']

In [42]:
df_lotus_select = df_lotus[['vehicle_weight', 'model_year']]

In [54]:
x = df_lotus_select.head(7)

In [55]:
x = np.asarray(x)
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [56]:
XTX = x.T @ x
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [57]:
w = np.linalg.pinv(XTX)
w

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [58]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.asarray(y)
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [59]:
q = (w @ x.T)@y
q

array([0.13644777, 0.2327492 ])

In [60]:
0.13644777 + 0.2327492

0.36919696999999996